/* QUESTION
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

//SOLUTION
#include <iostream>
using namespace std;
#define END 4000000
int main(){
  int n1, n2, next;
  int sum;
  n1 = 1;
  n2 = 2;
  cout << "Print fib: ";
  for(int i = 1; ; i++){
    if(n1 > END){
      break;
    }
    if(n1 % 2 == 0){
      sum += n1;
    }
    //cout << n1 << " ";
    next = n1 + n2;
    n1 = n2;
    n2 = next;
  }
  cout << "SUM: " << sum;
  cout << endl;
}
